spring:
  kafka:
    consumer:
      group-id: userGroup, reviewGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: userVerification:com.yuzarsif.contextshare.notificationservice.kafka.user.UserVerification, reviewNotification:com.yuzarsif.contextshare.notificationservice.kafka.review.ReviewNotification
  profiles:
    active: dev

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true