spring:
  profiles:
    active: ${ACTIVE_PROFILE}
  application:
    name: GAME-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      springframework:
        retry: INFO

