spring:
  application:
    name: GAME-SERVICE
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/game-db
    username: root
    password: yuzarsif
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
  data:
    mongodb:
      uri: mongodb+srv://yuzarsifkilic:PyBJnq8AO88FeAQ0@cluster0.8yl9pa2.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: context_share


