spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3312/user-db
    username: root
    password: yuzarsif
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: userVerification:com.yuzarsif.contextshare.userservice.kafka.UserVerification

server:
  port: 8084

jwt:
  key: 5b5YqfHs3KfJg9qH5OZwQ2O1z5pGv9oJmsqpe8T/tQ8=
