spring:
  data:
    mongodb:
      username: yuzarsif
      password: yuzarsif
      host: localhost
      port: 27018
      database: reviews
      authentication-database: admin

server:
  port: 8083

clients:
  user-service: http://localhost:8084
  game-service: http://localhost:8086