name: Game Service API Pipeline

on:
  push:
    branches:
      - master
      - game-service
    paths:
      - game-service/**
      - .github/workflows/game-service.yml

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Grant execute permission for mvnw file
        run: chmod +x game-service/mvnw
      - name: Compile Project
        run: |
          cd game-service
          ./mvnw clean compile

  build-image:
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Grant execute permission for mvnw file
        run: chmod +x game-service/mvnw

      - name: Extract Project Version
        id: extract_version
        run: |
          cd game-service
          VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=VERSION::$VERSION"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: api
          file: game-service/Dockerfile
          push: true
          tags: |
            ${{secrets.DOCKER_USERNAME}}/api:${{ steps.extract_version.outputs.VERSION }}
            ${{secrets.DOCKER_USERNAME}}/api:latest
          build-args: |
            APP_VERSION=${{ steps.extract_version.outputs.VERSION }}
            MYSQL_URL=${{ secrets.GAMEDB_URL }}
            MYSQL_PASSWORD=${{ secrets.GAMEDB_PASSWORD }}
            MONGODB_URL=${{ secrets.GAMEDB_MONGO_URL }}
